run:
  skip-files:
    - ".*/gen/.*\\.pb\\.go$"
    - ".*/gen/.*\\.connect\\.go$"
    - ".*/sdk/go1.21.0/src/.*\\.go$"
output:
  format: colored-line-number
linters-settings:
  govet:
    enable-all: true
    disable:
      - fieldalignment
      - loopclosure
      - shadow
  revive:
    rules:
      - name: var-naming
        arguments:
          - ["ListGolinksByUrl"]
          - []
linters:
  enable-all: true
  disable:
    # Temporarily disabled linters
    - ireturn
    - revive
    - bodyclose
    - contextcheck
    - cyclop
    - errorlint
    - exhaustruct
    - goerr113
    - gomnd
    - interfacebloat
    - stylecheck

    # Unpreferred linters
    - depguard
    - gochecknoglobals
    - godox
    - nlreturn
    - paralleltest
    - typecheck
    - varnamelen
    - wsl

    # Deprecated linters
    - deadcode
    - exhaustivestruct
    - ifshort
    - interfacer
    - golint
    - maligned
    - nosnakecase
    - varcheck
    - scopelint
    - structcheck
issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - containedctx
        - dogsled
        - dupl
        - exhaustruct
        - funlen
        - noctx
        - testpackage
    - path: clog/level\.go
      linters:
        - exhaustive
    - path: clog/clog\.go
      linters:
        - gci
        - gochecknoinits
        - forcetypeassert
    - path: clog/cloud_logging\.go
      linters:
        - gci
    - path: clog/logger\.go
      linters:
        - gci
    - path: clog/replacers\.go
      linters:
        - forcetypeassert
    - path: clog/clogcontext/handler\.go
      linters:
        - gci
        - forcetypeassert
    - path: middleware/http_logger.go
      linters:
        - forcetypeassert
        - nestif
        - wrapcheck
