import type { Metadata } from "next";
import ThemeRegistry from "./components/ThemeRegistry/ThemeRegistry";
import { Link as LinkIcon } from "@mui/icons-material";
import { AppBar, Toolbar, Typography } from "@mui/material";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ThemeRegistry>
          <AppBar position="fixed">
            <Toolbar>
              <LinkIcon />
              <Typography variant="h6" noWrap component="div">
                Golink
              </Typography>
            </Toolbar>
          </AppBar>
          {children}
        </ThemeRegistry>
      </body>
    </html>
  );
}
