runtime: nodejs18
instance_class: F1
automatic_scaling:
  target_cpu_utilization: 0.95
  target_throughput_utilization: 0.95
  min_idle_instances: 0
  max_idle_instances: 1
  min_instances: 0
  max_instances: 1
  min_pending_latency: 5000ms
  max_pending_latency: automatic
  max_concurrent_requests: 100
handlers:
  - url: /c/favicon.ico
    secure: always
    static_files: public/favicon.ico
    upload: public/favicon\.ico
  - url: /c/static
    secure: always
    static_dir: public/static
    expiration: 1d
  - url: /c/.*
    secure: always
    script: auto
service: console
