app_engine_apis: true
runtime: go120
instance_class: F1
automatic_scaling:
  target_cpu_utilization: 0.95
  target_throughput_utilization: 0.95
  min_idle_instances: 0
  max_idle_instances: 1
  min_instances: 0
  max_instances: 1
  min_pending_latency: 5000ms
  max_pending_latency: automatic
  max_concurrent_requests: 100
handlers:
  - url: /.*
    script: auto
    secure: always
    redirect_http_response_code: 301
main: ./cmd/api
service: api
env_variables:
  ALLOWED_ORIGINS: chrome-extension://clecngohjeflemkblbfdfbjkjnigbjok
