name: backend ci

on:
  pull_request:
    paths:
      - backend/**/*.go
      - backend/go.mod
      - backend/go.sum
      - .golangci.yaml
      - .github/workflows/backend-on-pr.yaml
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    env:
      GOEXPERIMENT: loopvar
    steps:
      - uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4
      - uses: actions/setup-go@cd53bc84d5e2fd85362f4cb840513e06427082d3 # v4
        with:
          go-version: "1.21.13"
      - run: go mod download
      - name: Firestore Emulator
        run: docker run -d -p 9000:9000 gcr.io/google.com/cloudsdktool/cloud-sdk:emulators gcloud emulators firestore start --host-port=0.0.0.0:9000
      - run: go build -v ./...
      - run: go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...
        env:
          FIRESTORE_EMULATOR_HOST: "localhost:9000"
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@ab904c41d6ece82784817410c45d8b8c02684457 # v3
        env:
          directory: ./backend
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  golangci-lint:
    runs-on: ubuntu-latest
    env:
      GOEXPERIMENT: loopvar
    steps:
      - uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4
      - uses: actions/setup-go@cd53bc84d5e2fd85362f4cb840513e06427082d3 # v4
        with:
          go-version: "1.21.13"
      - name: golangci-lint
        uses: golangci/golangci-lint-action@3a919529898de77ec3da873e3063ca4b10e7f5cc # v3
        with:
          working-directory: ./backend
          skip-cache: true
          version: v1.53.3
          args: --config=.golangci.yaml