name: backend on pr

on:
  pull_request:
    paths:
      - backend/**/*.go
      - backend/go.mod
      - backend/go.sum
      - .golangci.yaml
      - .github/workflows/backend-on-pr.yaml

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    env:
      GOEXPERIMENT: loopvar
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: "1.21"
      - run: go mod download
      - name: Firestore Emulator
        run: docker run -d -p 9000:9000 gcr.io/google.com/cloudsdktool/cloud-sdk:emulators gcloud emulators firestore start --host-port=0.0.0.0:9000
      - run: go build -v ./...
      - run: go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...
        env:
          FIRESTORE_EMULATOR_HOST: "localhost:9000"
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          directory: ./backend
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  golangci-lint:
    runs-on: ubuntu-latest
    env:
      GOEXPERIMENT: loopvar
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: "1.21"
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          working-directory: ./backend
          skip-cache: true
          version: v1.53.3
          args: --config=.golangci.yaml